### ISSUE TITLE
The readme needs a live example

### ISSUE THREAD

**Issue by AlexandreBonneau** [xxRockOnxx/vue-flexi-table#1]
Hey, the readme is fine as it is, but a link to a live example would make it even better!

**Comment by xxRockOnxx** [comment]
I am currently making one and there will a lot of fixes to be released :)

**Comment by AlexandreBonneau** [comment]
cool ;)

**Comment by xxRockOnxx** [comment]
Here you go :)
https://github.com/xxRockOnxx/vue-flexi-table/commit/d21191b2216444972cbbbb997e2d4adb6fd0f598
Link: https://xxrockonxx.github.io/vue-flexi-table/demo/index.html#/

**Comment by AlexandreBonneau** [comment]
nice!
