### ISSUE TITLE
Properties are not connected in the demo 

### ISSUE THREAD

**Issue by Claus1** [xxRockOnxx/vue-flexi-table#3]
I am a beginner in vue  and tried to reuse the demo in my project, just changed the request path and column names and got a  lot of mistakes. What a problem can be? The request worked ok and returned list of objects.  dtMixin is declared and used without console mistakes.

Execution mistakes:
>>>
[Vue warn]: Property or method "dtPage" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data option.

found in

---> <Index> at c:\MyProjects\adminsema\client\views\diseases\index.vue
       <AppMain> at c:\MyProjects\adminsema\client\components\layout\AppMain.vue
         <Root>  1:476:7
[Vue warn]: Property or method "dtPerPage" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data option.

found in

---> <Index> at c:\MyProjects\adminsema\client\views\diseases\index.vue
       <AppMain> at c:\MyProjects\adminsema\client\components\layout\AppMain.vue
         <Root>  1:476:7
[Vue warn]: Property or method "dtLengthChange" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data option.

found in

---> <Index> at c:\MyProjects\adminsema\client\views\diseases\index.vue
       <AppMain> at c:\MyProjects\adminsema\client\components\layout\AppMain.vue
         <Root>  1:476:7
[Vue warn]: Property or method "dtStart" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data option.

found in

---> <Index> at c:\MyProjects\adminsema\client\views\diseases\index.vue
       <AppMain> at c:\MyProjects\adminsema\client\components\layout\AppMain.vue
         <Root>  1:476:7
[Vue warn]: Property or method "dtEnd" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data option.

found in

---> <Index> at c:\MyProjects\adminsema\client\views\diseases\index.vue
       <AppMain> at c:\MyProjects\adminsema\client\components\layout\AppMain.vue
         <Root>  1:476:7
[Vue warn]: Property or method "dtTotalRecords" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data option.

found in

---> <Index> at c:\MyProjects\adminsema\client\views\diseases\index.vue
       <AppMain> at c:\MyProjects\adminsema\client\components\layout\AppMain.vue
         <Root>  1:476:7
[Vue warn]: Property or method "dtTotalPages" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data option.

found in

---> <Index> at c:\MyProjects\adminsema\client\views\diseases\index.vue
       <AppMain> at c:\MyProjects\adminsema\client\components\layout\AppMain.vue
         <Root>  1:476:7
[Vue warn]: Property or method "dtPage" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data option.

found in

---> <Index> at c:\MyProjects\adminsema\client\views\diseases\index.vue
       <AppMain> at c:\MyProjects\adminsema\client\components\layout\AppMain.vue
         <Root>  1:476:7
[Vue warn]: Property or method "dtPagination" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data option.

found in

---> <Index> at c:\MyProjects\adminsema\client\views\diseases\index.vue
       <AppMain> at c:\MyProjects\adminsema\client\components\layout\AppMain.vue
         <Root>  1:476:7
[Vue warn]: Property or method "dtGoPrev" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data option.

found in

---> <Index> at c:\MyProjects\adminsema\client\views\diseases\index.vue
       <AppMain> at c:\MyProjects\adminsema\client\components\layout\AppMain.vue
         <Root>  1:476:7
[Vue warn]: Property or method "dtGoPage" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data option.

found in

---> <Index> at c:\MyProjects\adminsema\client\views\diseases\index.vue
       <AppMain> at c:\MyProjects\adminsema\client\components\layout\AppMain.vue
         <Root>  1:476:7
[Vue warn]: Property or method "dtGoNext" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data option.

found in

---> <Index> at c:\MyProjects\adminsema\client\views\diseases\index.vue
       <AppMain> at c:\MyProjects\adminsema\client\components\layout\AppMain.vue
         <Root>  1:476:7
[Vue warn]: Invalid prop: type check failed for prop "page". Expected Number, got Undefined.

found in

---> <FlexiTable> at c:\MyProjects\adminsema\node_modules\vue-flexi-table\src\Table.vue
       <Index> at c:\MyProjects\adminsema\client\views\diseases\index.vue
         <AppMain> at c:\MyProjects\adminsema\client\components\layout\AppMain.vue
           <Root>  1:476:7
[Vue warn]: Invalid handler for event "change": got undefined

found in

---> <FlexiTableLengthControl> at c:\MyProjects\adminsema\node_modules\vue-flexi-table\src\LengthControl.vue
       <Index> at c:\MyProjects\adminsema\client\views\diseases\index.vue
         <AppMain> at c:\MyProjects\adminsema\client\components\layout\AppMain.vue
           <Root>  1:476:7
[Vue warn]: Invalid prop: type check failed for prop "start". Expected Number, got Undefined.

found in

---> <FlexiTableLength> at c:\MyProjects\adminsema\node_modules\vue-flexi-table\src\Length.vue
       <Index> at c:\MyProjects\adminsema\client\views\diseases\index.vue
         <AppMain> at c:\MyProjects\adminsema\client\components\layout\AppMain.vue
           <Root>  1:476:7
[Vue warn]: Invalid prop: type check failed for prop "end". Expected Number, got Undefined.

found in

---> <FlexiTableLength> at c:\MyProjects\adminsema\node_modules\vue-flexi-table\src\Length.vue
       <Index> at c:\MyProjects\adminsema\client\views\diseases\index.vue
         <AppMain> at c:\MyProjects\adminsema\client\components\layout\AppMain.vue
           <Root>  1:476:7
[Vue warn]: Invalid prop: type check failed for prop "total". Expected Number, got Undefined.

found in

---> <FlexiTableLength> at c:\MyProjects\adminsema\node_modules\vue-flexi-table\src\Length.vue
       <Index> at c:\MyProjects\adminsema\client\views\diseases\index.vue
         <AppMain> at c:\MyProjects\adminsema\client\components\layout\AppMain.vue
           <Root>  1:476:7
[Vue warn]: Invalid handler for event "prevClick": got undefined

found in

---> <FlexiTablePagination> at c:\MyProjects\adminsema\node_modules\vue-flexi-table\src\Pagination.vue
       <Index> at c:\MyProjects\adminsema\client\views\diseases\index.vue
         <AppMain> at c:\MyProjects\adminsema\client\components\layout\AppMain.vue
           <Root>  1:476:7
[Vue warn]: Invalid handler for event "pageClick": got undefined

found in

---> <FlexiTablePagination> at c:\MyProjects\adminsema\node_modules\vue-flexi-table\src\Pagination.vue
       <Index> at c:\MyProjects\adminsema\client\views\diseases\index.vue
         <AppMain> at c:\MyProjects\adminsema\client\components\layout\AppMain.vue
           <Root>  1:476:7
[Vue warn]: Invalid handler for event "nextClick": got undefined

found in

---> <FlexiTablePagination> at c:\MyProjects\adminsema\node_modules\vue-flexi-table\src\Pagination.vue
       <Index> at c:\MyProjects\adminsema\client\views\diseases\index.vue
         <AppMain> at c:\MyProjects\adminsema\client\components\layout\AppMain.vue
           <Root>  1:476:7
[Vue warn]: Invalid prop: type check failed for prop "currentPage". Expected Number, got Undefined.

found in

---> <FlexiTablePagination> at c:\MyProjects\adminsema\node_modules\vue-flexi-table\src\Pagination.vue
       <Index> at c:\MyProjects\adminsema\client\views\diseases\index.vue
         <AppMain> at c:\MyProjects\adminsema\client\components\layout\AppMain.vue
           <Root>  1:476:7
[Vue warn]: Invalid prop: type check failed for prop "totalPages". Expected Number, got Undefined.

found in

---> <FlexiTablePagination> at c:\MyProjects\adminsema\node_modules\vue-flexi-table\src\Pagination.vue
       <Index> at c:\MyProjects\adminsema\client\views\diseases\index.vue
         <AppMain> at c:\MyProjects\adminsema\client\components\layout\AppMain.vue
           <Root>  1:476:7
[Vue warn]: Invalid prop: type check failed for prop "pages". Expected Array, got Undefined.

found in

---> <FlexiTablePagination> at c:\MyProjects\adminsema\node_modules\vue-flexi-table\src\Pagination.vue
       <Index> at c:\MyProjects\adminsema\client\views\diseases\index.vue
         <AppMain> at c:\MyProjects\adminsema\client\components\layout\AppMain.vue
           <Root>  1:476:7
[Vue warn]: Property or method "dtPage" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data option.

found in

---> <Index> at c:\MyProjects\adminsema\client\views\diseases\index.vue
       <AppMain> at c:\MyProjects\adminsema\client\components\layout\AppMain.vue
         <Root>  1:476:7
[Vue warn]: Property or method "dtPerPage" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data option.

found in

---> <Index> at c:\MyProjects\adminsema\client\views\diseases\index.vue
       <AppMain> at c:\MyProjects\adminsema\client\components\layout\AppMain.vue
         <Root>  1:476:7
[Vue warn]: Property or method "dtLengthChange" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data option.

found in

---> <Index> at c:\MyProjects\adminsema\client\views\diseases\index.vue
       <AppMain> at c:\MyProjects\adminsema\client\components\layout\AppMain.vue
         <Root>  1:476:7
[Vue warn]: Property or method "dtStart" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data option.

found in

---> <Index> at c:\MyProjects\adminsema\client\views\diseases\index.vue
       <AppMain> at c:\MyProjects\adminsema\client\components\layout\AppMain.vue
         <Root>  1:476:7
[Vue warn]: Property or method "dtEnd" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data option.

found in

---> <Index> at c:\MyProjects\adminsema\client\views\diseases\index.vue
       <AppMain> at c:\MyProjects\adminsema\client\components\layout\AppMain.vue
         <Root>  1:476:7
[Vue warn]: Property or method "dtTotalRecords" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data option.

found in

---> <Index> at c:\MyProjects\adminsema\client\views\diseases\index.vue
       <AppMain> at c:\MyProjects\adminsema\client\components\layout\AppMain.vue
         <Root>  1:476:7
[Vue warn]: Property or method "dtTotalPages" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data option.

found in

---> <Index> at c:\MyProjects\adminsema\client\views\diseases\index.vue
       <AppMain> at c:\MyProjects\adminsema\client\components\layout\AppMain.vue
         <Root>  1:476:7
[Vue warn]: Property or method "dtPage" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data option.

found in

---> <Index> at c:\MyProjects\adminsema\client\views\diseases\index.vue
       <AppMain> at c:\MyProjects\adminsema\client\components\layout\AppMain.vue
         <Root>  1:476:7
[Vue warn]: Property or method "dtPagination" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data option.

found in

---> <Index> at c:\MyProjects\adminsema\client\views\diseases\index.vue
       <AppMain> at c:\MyProjects\adminsema\client\components\layout\AppMain.vue
         <Root>  1:476:7
[Vue warn]: Property or method "dtGoPrev" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data option.

found in

---> <Index> at c:\MyProjects\adminsema\client\views\diseases\index.vue
       <AppMain> at c:\MyProjects\adminsema\client\components\layout\AppMain.vue
         <Root>  1:476:7
[Vue warn]: Property or method "dtGoPage" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data option.

found in

---> <Index> at c:\MyProjects\adminsema\client\views\diseases\index.vue
       <AppMain> at c:\MyProjects\adminsema\client\components\layout\AppMain.vue
         <Root>  1:476:7
[Vue warn]: Property or method "dtGoNext" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data option.

found in

---> <Index> at c:\MyProjects\adminsema\client\views\diseases\index.vue
       <AppMain> at c:\MyProjects\adminsema\client\components\layout\AppMain.vue
         <Root>  1:476:7
[Vue warn]: Invalid prop: type check failed for prop "page". Expected Number, got Undefined.

found in

---> <FlexiTable> at c:\MyProjects\adminsema\node_modules\vue-flexi-table\src\Table.vue
       <Index> at c:\MyProjects\adminsema\client\views\diseases\index.vue
         <AppMain> at c:\MyProjects\adminsema\client\components\layout\AppMain.vue
           <Root>  1:476:7
[Vue warn]: Invalid handler for event "change": got undefined

found in

---> <FlexiTableLengthControl> at c:\MyProjects\adminsema\node_modules\vue-flexi-table\src\LengthControl.vue
       <Index> at c:\MyProjects\adminsema\client\views\diseases\index.vue
         <AppMain> at c:\MyProjects\adminsema\client\components\layout\AppMain.vue
           <Root>  1:476:7
[Vue warn]: Invalid prop: type check failed for prop "start". Expected Number, got Undefined.

found in

---> <FlexiTableLength> at c:\MyProjects\adminsema\node_modules\vue-flexi-table\src\Length.vue
       <Index> at c:\MyProjects\adminsema\client\views\diseases\index.vue
         <AppMain> at c:\MyProjects\adminsema\client\components\layout\AppMain.vue
           <Root>  1:476:7
[Vue warn]: Invalid prop: type check failed for prop "end". Expected Number, got Undefined.

found in

---> <FlexiTableLength> at c:\MyProjects\adminsema\node_modules\vue-flexi-table\src\Length.vue
       <Index> at c:\MyProjects\adminsema\client\views\diseases\index.vue
         <AppMain> at c:\MyProjects\adminsema\client\components\layout\AppMain.vue
           <Root>  1:476:7
[Vue warn]: Invalid prop: type check failed for prop "total". Expected Number, got Undefined.

found in

---> <FlexiTableLength> at c:\MyProjects\adminsema\node_modules\vue-flexi-table\src\Length.vue
       <Index> at c:\MyProjects\adminsema\client\views\diseases\index.vue
         <AppMain> at c:\MyProjects\adminsema\client\components\layout\AppMain.vue
           <Root>  1:476:7
[Vue warn]: Invalid prop: type check failed for prop "currentPage". Expected Number, got Undefined.

found in

---> <FlexiTablePagination> at c:\MyProjects\adminsema\node_modules\vue-flexi-table\src\Pagination.vue
       <Index> at c:\MyProjects\adminsema\client\views\diseases\index.vue
         <AppMain> at c:\MyProjects\adminsema\client\components\layout\AppMain.vue
           <Root>  1:476:7
[Vue warn]: Invalid prop: type check failed for prop "totalPages". Expected Number, got Undefined.

found in

---> <FlexiTablePagination> at c:\MyProjects\adminsema\node_modules\vue-flexi-table\src\Pagination.vue
       <Index> at c:\MyProjects\adminsema\client\views\diseases\index.vue
         <AppMain> at c:\MyProjects\adminsema\client\components\layout\AppMain.vue
           <Root>  1:476:7
[Vue warn]: Invalid prop: type check failed for prop "pages". Expected Array, got Undefined.

found in

---> <FlexiTablePagination> at c:\MyProjects\adminsema\node_modules\vue-flexi-table\src\Pagination.vue
       <Index> at c:\MyProjects\adminsema\client\views\diseases\index.vue
         <AppMain> at c:\MyProjects\adminsema\client\components\layout\AppMain.vue
           <Root>  1:476:7
[Vue warn]: Invalid handler for event "prevClick": got undefined

found in

---> <FlexiTablePagination> at c:\MyProjects\adminsema\node_modules\vue-flexi-table\src\Pagination.vue
       <Index> at c:\MyProjects\adminsema\client\views\diseases\index.vue
         <AppMain> at c:\MyProjects\adminsema\client\components\layout\AppMain.vue
           <Root>  1:476:7
[Vue warn]: Invalid handler for event "pageClick": got undefined

found in

---> <FlexiTablePagination> at c:\MyProjects\adminsema\node_modules\vue-flexi-table\src\Pagination.vue
       <Index> at c:\MyProjects\adminsema\client\views\diseases\index.vue
         <AppMain> at c:\MyProjects\adminsema\client\components\layout\AppMain.vue
           <Root>  1:476:7
[Vue warn]: Invalid handler for event "nextClick": got undefined

found in

---> <FlexiTablePagination> at c:\MyProjects\adminsema\node_modules\vue-flexi-table\src\Pagination.vue
       <Index> at c:\MyProjects\adminsema\client\views\diseases\index.vue
         <AppMain> at c:\MyProjects\adminsema\client\components\layout\AppMain.vue
           <Root>  1:476:7
[Vue warn]: Property or method "dtPage" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data option.

found in

---> <Index> at c:\MyProjects\adminsema\client\views\diseases\index.vue
       <AppMain> at c:\MyProjects\adminsema\client\components\layout\AppMain.vue
         <Root>  1:476:7
[Vue warn]: Property or method "dtPerPage" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data option.

found in

---> <Index> at c:\MyProjects\adminsema\client\views\diseases\index.vue
       <AppMain> at c:\MyProjects\adminsema\client\components\layout\AppMain.vue
         <Root>  1:476:7
[Vue warn]: Property or method "dtLengthChange" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data option.

found in

---> <Index> at c:\MyProjects\adminsema\client\views\diseases\index.vue
       <AppMain> at c:\MyProjects\adminsema\client\components\layout\AppMain.vue
         <Root>  1:476:7
[Vue warn]: Property or method "dtStart" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data option.

found in

---> <Index> at c:\MyProjects\adminsema\client\views\diseases\index.vue
       <AppMain> at c:\MyProjects\adminsema\client\components\layout\AppMain.vue
         <Root>  1:476:7
[Vue warn]: Property or method "dtEnd" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data option.

found in

---> <Index> at c:\MyProjects\adminsema\client\views\diseases\index.vue
       <AppMain> at c:\MyProjects\adminsema\client\components\layout\AppMain.vue
         <Root>  1:476:7
[Vue warn]: Property or method "dtTotalRecords" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data option.

found in

---> <Index> at c:\MyProjects\adminsema\client\views\diseases\index.vue
       <AppMain> at c:\MyProjects\adminsema\client\components\layout\AppMain.vue
         <Root>  1:476:7
[Vue warn]: Property or method "dtTotalPages" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data option.

found in

---> <Index> at c:\MyProjects\adminsema\client\views\diseases\index.vue
       <AppMain> at c:\MyProjects\adminsema\client\components\layout\AppMain.vue
         <Root>  1:476:7
[Vue warn]: Property or method "dtPage" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data option.

found in

---> <Index> at c:\MyProjects\adminsema\client\views\diseases\index.vue
       <AppMain> at c:\MyProjects\adminsema\client\components\layout\AppMain.vue
         <Root>  1:476:7
[Vue warn]: Property or method "dtPagination" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data option.

found in

---> <Index> at c:\MyProjects\adminsema\client\views\diseases\index.vue
       <AppMain> at c:\MyProjects\adminsema\client\components\layout\AppMain.vue
         <Root>  1:476:7
[Vue warn]: Property or method "dtGoPrev" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data option.

found in

---> <Index> at c:\MyProjects\adminsema\client\views\diseases\index.vue
       <AppMain> at c:\MyProjects\adminsema\client\components\layout\AppMain.vue
         <Root>  1:476:7
[Vue warn]: Property or method "dtGoPage" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data option.

found in

---> <Index> at c:\MyProjects\adminsema\client\views\diseases\index.vue
       <AppMain> at c:\MyProjects\adminsema\client\components\layout\AppMain.vue
         <Root>  1:476:7
[Vue warn]: Property or method "dtGoNext" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data option.

found in

---> <Index> at c:\MyProjects\adminsema\client\views\diseases\index.vue
       <AppMain> at c:\MyProjects\adminsema\client\components\layout\AppMain.vue
         <Root>  1:476:7
[Vue warn]: Invalid prop: type check failed for prop "page". Expected Number, got Undefined.

found in

---> <FlexiTable> at c:\MyProjects\adminsema\node_modules\vue-flexi-table\src\Table.vue
       <Index> at c:\MyProjects\adminsema\client\views\diseases\index.vue
         <AppMain> at c:\MyProjects\adminsema\client\components\layout\AppMain.vue
           <Root>  1:476:7
[Vue warn]: Invalid handler for event "change": got undefined

found in

---> <FlexiTableLengthControl> at c:\MyProjects\adminsema\node_modules\vue-flexi-table\src\LengthControl.vue
       <Index> at c:\MyProjects\adminsema\client\views\diseases\index.vue
         <AppMain> at c:\MyProjects\adminsema\client\components\layout\AppMain.vue
           <Root>  1:476:7
[Vue warn]: Invalid prop: type check failed for prop "start". Expected Number, got Undefined.

found in

---> <FlexiTableLength> at c:\MyProjects\adminsema\node_modules\vue-flexi-table\src\Length.vue
       <Index> at c:\MyProjects\adminsema\client\views\diseases\index.vue
         <AppMain> at c:\MyProjects\adminsema\client\components\layout\AppMain.vue
           <Root>  1:476:7
[Vue warn]: Invalid prop: type check failed for prop "end". Expected Number, got Undefined.

found in

---> <FlexiTableLength> at c:\MyProjects\adminsema\node_modules\vue-flexi-table\src\Length.vue
       <Index> at c:\MyProjects\adminsema\client\views\diseases\index.vue
         <AppMain> at c:\MyProjects\adminsema\client\components\layout\AppMain.vue
           <Root>  1:476:7
[Vue warn]: Invalid prop: type check failed for prop "total". Expected Number, got Undefined.

found in

---> <FlexiTableLength> at c:\MyProjects\adminsema\node_modules\vue-flexi-table\src\Length.vue
       <Index> at c:\MyProjects\adminsema\client\views\diseases\index.vue
         <AppMain> at c:\MyProjects\adminsema\client\components\layout\AppMain.vue
           <Root>  1:476:7
[Vue warn]: Invalid prop: type check failed for prop "currentPage". Expected Number, got Undefined.

found in

---> <FlexiTablePagination> at c:\MyProjects\adminsema\node_modules\vue-flexi-table\src\Pagination.vue
       <Index> at c:\MyProjects\adminsema\client\views\diseases\index.vue
         <AppMain> at c:\MyProjects\adminsema\client\components\layout\AppMain.vue
           <Root>  1:476:7
[Vue warn]: Invalid prop: type check failed for prop "totalPages". Expected Number, got Undefined.

found in

---> <FlexiTablePagination> at c:\MyProjects\adminsema\node_modules\vue-flexi-table\src\Pagination.vue
       <Index> at c:\MyProjects\adminsema\client\views\diseases\index.vue
         <AppMain> at c:\MyProjects\adminsema\client\components\layout\AppMain.vue
           <Root>  1:476:7
[Vue warn]: Invalid prop: type check failed for prop "pages". Expected Array, got Undefined.

found in

---> <FlexiTablePagination> at c:\MyProjects\adminsema\node_modules\vue-flexi-table\src\Pagination.vue
       <Index> at c:\MyProjects\adminsema\client\views\diseases\index.vue
         <AppMain> at c:\MyProjects\adminsema\client\components\layout\AppMain.vue
           <Root>  1:476:7
[Vue warn]: Invalid handler for event "prevClick": got undefined

found in

---> <FlexiTablePagination> at c:\MyProjects\adminsema\node_modules\vue-flexi-table\src\Pagination.vue
       <Index> at c:\MyProjects\adminsema\client\views\diseases\index.vue
         <AppMain> at c:\MyProjects\adminsema\client\components\layout\AppMain.vue
           <Root>  1:476:7
[Vue warn]: Invalid handler for event "pageClick": got undefined

found in

---> <FlexiTablePagination> at c:\MyProjects\adminsema\node_modules\vue-flexi-table\src\Pagination.vue
       <Index> at c:\MyProjects\adminsema\client\views\diseases\index.vue
         <AppMain> at c:\MyProjects\adminsema\client\components\layout\AppMain.vue
           <Root>  1:476:7
[Vue warn]: Invalid handler for event "nextClick": got undefined

found in

---> <FlexiTablePagination> at c:\MyProjects\adminsema\node_modules\vue-flexi-table\src\Pagination.vue
       <Index> at c:\MyProjects\adminsema\client\views\diseases\index.vue
         <AppMain> at c:\MyProjects\adminsema\client\components\layout\AppMain.vue
           <Root>  1:476:7

**Comment by xxRockOnxx** [comment]
you declared the mixin (assuming you mean import or require) but did you registered it?

`mixins: [dtMixins]` ?

**Comment by Claus1** [comment]
yes. I did. I even removed slots in a table description

<flexi-table :columns="columns" :rows="formattedRows" :query="query" :search="searchOption" :page="dtPage" :perPage="dtPerPage">
      

    </flexi-table>

Does not help.

**Comment by Claus1** [comment]
I changed file index.js because it was not compiled in my configuration.
so now it is
exports. dtMixins = require( './mixins')
exports. Length = require( './Length.vue')
exports. LengthControl = require( './LengthControl.vue')
exports. Pagination = require( './Pagination.vue')
exports. Table = require( './Table.vue')
exports. Tools = require( './Tools.vue')

**Comment by xxRockOnxx** [comment]
I guess this is solved now and will close the issue. I forgot that this was es6. Not sure if I'll fix this and continue this as it have some flaws. There's not a lot who uses this anyway. I'll keep the repo up tho and will welcome PRs.

Table is a very complex component and it's not a one size fits all unless for basic table only... and that defeats the 'flex-table' name of the package.

**Comment by Claus1** [comment]
nope, I changed index.js before the  issue. Probably I am so lucky that found a bug in vue. The mixin does not work in my case.
